### ISSUE TITLE
Issues when building universal python versions

### ISSUE THREAD

**Issue by vighneshbirodkar** [ogrisel/wheelhouse-uploader#16]
For [project-template](https://github.com/scikit-learn-contrib/project-template) I am trying to build and upload windows wheels over here:
https://ci.appveyor.com/project/vighneshbirodkar/project-template

When there is a python tag like py2 or py3 in the .whl file [this line](https://github.com/ogrisel/wheelhouse-uploader/blob/master/wheelhouse_uploader/utils.py#L101) evaluates to true and the file is skipped. For example
```shell
$ find dist/
dist/
dist/sklearn_template-0.0.3-py2-none-any.whl

$ python -m wheelhouse_uploader upload --no-ssl-check --local-folder=dist sklearn-template-trial
/usr/local/lib/python2.7/dist-packages/libcloud/httplib_ssl.py:229: UserWarning: SSL certificate verification is disabled, this can pose a security risk. For more information how to enable the SSL certificate verification, please visit the libcloud documentation.
  warnings.warn(libcloud.security.VERIFY_SSL_DISABLED_MSG)
Skipping sklearn_template-0.0.3-py2-none-any.whl: Invalid wheel filename sklearn_template-0.0.3-py2-none-any.whl
About to upload 0 files
Uploading metadata.json with 3 entries
Updating index.html with 3 links
Wheelhouse successfully published at:
http://21172a4830ee235601c0-49c8cc9fec985e30830ceced7e8dcbe2.r58.cf2.rackcdn.com
```

Also the detection of `-` character [here](https://github.com/ogrisel/wheelhouse-uploader/blob/master/wheelhouse_uploader/utils.py#L133) makes it so that [32bit exes are skipped](https://ci.appveyor.com/project/vighneshbirodkar/project-template/build/1.0.23/job/kjr3l1k49u4j7pdi#L181) and [64bit exes are uploaded](https://ci.appveyor.com/project/vighneshbirodkar/project-template/build/1.0.23/job/t04mdv4q2en4s4dy#L189)

This only happens with projects having pure python code. I can submit a bug fix, but some pointers on how to handle this would be appreciated.
@ogrisel

**Comment by ogrisel** [comment]
Thanks for the report. The code that parses the filenames is here:

https://github.com/ogrisel/wheelhouse-uploader/blob/master/wheelhouse_uploader/utils.py#L18

Please add a new test case for your filenames in the dosctring. You can launch the doctest by calling nosetests on this file.
