### ISSUE TITLE
Upload directly to pypi? 

### ISSUE THREAD

**Issue by alexlenail** [ogrisel/wheelhouse-uploader#20]
For the purposes of my project, I'd like to deploy wheels that my travis file is building directly to pypi without having to upload them to a cloud as an intermediate. Is that possible using wheelhouse-uploader? If not, would it be a feature you would be willing to add?

**Comment by hugovk** [comment]
@alexlenail Can you use the Travis deploy feature for this? 

https://docs.travis-ci.com/user/deployment/pypi/

Or twine? 

https://twine.readthedocs.io/en/latest/

**Comment by alexlenail** [comment]
I believe I solved this with https://github.com/joerick/cibuildwheel
